---
title: "Homework 9"
author: "Christophe Hunt"
date: "April 1, 2017"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
always_allow_html: yes  
---

\newpage

# Page 385: problem 1 a

Using the definition provided for the movement diagram, determine whether the following zero-sum games have a pure strategy Nash equilibrium. If the game does have a pure strategy Nash equilibrium, state the Nash equilibrium. Assume the row player is maximizing his playoffs which are showing in the matrices below.

\begin{table}[!h]
\centering
\begin{tabular}{lllc}
 &  & \multicolumn{2}{l}{Colin} \\ \cline{3-4}
 &  & C1 & \multicolumn{1}{l}{C2} \\ \hline
Rose & R1 & \multicolumn{1}{c}{10} & 10 \\
 & R2 & \multicolumn{1}{c}{5} & 0 \\ \hline
\end{tabular}
\end{table}

```{r, fig.height= 3, warning=FALSE, message=FALSE, cache=TRUE}
library(DiagrammeR)
grViz("digraph boxes {

  graph [overlap = true, fontsize = 8]

  node [shape = box]

  A [label = 'C1, R1 \n (10)']; 
  B [label = 'C1, R2 \n (5)']; 
  C [label = 'C2, R1 \n (10)']; 
  D [label = 'C2, R2 \n (0)']; 

  # several 'edge' statements
  B->A C->A D->B D->C
}
")
```

We do have a pure strategy Nash equilibrium of 10 as our arrows all point to one value, when Rose plays strategy 1 and Colin plays either strategy 1 or 2. For graphing similicity I set the strategy to Rose 1 and Colin 1.  

\newpage

# Page 385: problem 1 c

Using the definition provided for the movement diagram, determine whether the following zero-sum games have a pure strategy Nash equilibrium. If the game does have a pure strategy Nash equilibrium, state the Nash equilibrium. Assume the row player is maximizing his playoffs which are showing in the matrices below.

\begin{table}[!h]
\centering
\begin{tabular}{lllc}
 &  & \multicolumn{2}{l}{Colin} \\ \cline{3-4}
 &  & C1 & \multicolumn{1}{l}{C2} \\ \hline
Rose & R1 & \multicolumn{1}{c}{1/2} & 1/2 \\
 & R2 & \multicolumn{1}{c}{1} & 0 \\ \hline
\end{tabular}
\end{table}

# Page 404: problem 2 a

For problems a-g build a linear programming model for each player's decisions and solve it both geometrically and algebraically. Assume the row player is maximizing his playoffs which are showing in the matrices below. 

\begin{table}[!h]
\centering
\begin{tabular}{lllc}
 &  & \multicolumn{2}{l}{Colin} \\ \cline{3-4}
 &  & C1 & \multicolumn{1}{l}{C2} \\ \hline
Rose & R1 & \multicolumn{1}{c}{10} & 10 \\
 & R2 & \multicolumn{1}{c}{5} & 0 \\ \hline
\end{tabular}
\end{table}

# Page 413: problem 3

We are considering three alternatives A, B, and C under states of nature 1, 2 ,3, and 4, set up and solve both the investor's and nature's game:

\begin{table}[!h]
\centering
\begin{tabular}{crrrr}
\multicolumn{5}{l}{\textbf{States of Nature}} \\ \hline
\begin{tabular}[c]{@{}c@{}}Investor's choices \\ Alternatives\end{tabular} & \multicolumn{1}{c}{Condition \#1} & \multicolumn{1}{c}{Condition \#2} & \multicolumn{1}{c}{Condition \#3} & \multicolumn{1}{l}{Condition \#4} \\ \hline
A & 1100 & 900 & 400 & 300 \\
B & 850 & 1500 & 1000 & 500 \\
C & 700 & 1200 & 500 & 900 \\ \hline
\end{tabular}
\end{table}

# Page 420: problem 1

In the following problems, use the maximim and minimax method and movement diagram to determine if any pure strategy solution exist. Assume the row player is maximizing his payoffs which are shown in the matrices below. 

\begin{table}[!h]
\centering
\begin{tabular}{lllc}
 &  & \multicolumn{2}{l}{Colin} \\ \cline{3-4}
 &  & C1 & \multicolumn{1}{l}{C2} \\ \hline
Rose & R1 & \multicolumn{1}{c}{10} & 10 \\
 & R2 & \multicolumn{1}{c}{5} & 0 \\ \hline
\end{tabular}
\end{table}


# Page 428: problem 3

Using the alternative methods (a) equating expected value and (b) methods of oddments to find the solutions to the following games. Assume the row player is maximizing his payoffs which are shown in the matrices below. 

\begin{table}[!h]
\centering
\begin{tabular}{lllc}
 &  & \multicolumn{2}{l}{Colin} \\ \cline{3-4}
 &  & C1 & \multicolumn{1}{l}{C2} \\ \hline
Rose & R1 & \multicolumn{1}{c}{0.5} & 0.3 \\
 & R2 & \multicolumn{1}{c}{0.6} & 1 \\ \hline
\end{tabular}
\end{table}

# Page 440: problem 2

Use movements diagrams to find all the stable outcomes in Problems 1 through 5. Then use strategic moves (using Table 10.2) to determine if Rose can get a better outcome. 

\begin{table}[!h]
\centering
\begin{tabular}{lllc}
 &  & \multicolumn{2}{l}{Colin} \\ \cline{3-4}
 &  & C1 & \multicolumn{1}{l}{C2} \\ \hline
Rose & R1 & \multicolumn{1}{c}{(1,2)} & (3,1) \\
 & R2 & \multicolumn{1}{c}{(2, 4)} & (4, 3)\\ \hline
\end{tabular}
\end{table}


# Page 454: problem 3
