---
title: "Web API"
author: ""
date: ""
output: 
  html_document:
    theme: readable
    highlight: haddock
runtime: shiny
---

```{r, include = FALSE}
library(RJSONIO)
library(knitr)
library(data.table)
library(shiny)
library(pander)
library(gridExtra)

API_KEY <- "0c02c73bb17f1ce9799ba93ee8b58b45:5:72746030"
```

```{r, echo = FALSE, results='asis'}
library(shiny)

inputPanel(textInput(inputId = "key_words", "Keywords to Search NYT API:", "CUNY"),
           dateInput("beginning_date",label = 'Beginning Date input: yyyy-mm-dd', value = Sys.Date()-100),
           dateInput("end_date",label = 'End Date input: yyyy-mm-dd', value = Sys.Date()))
          
beginning_dateInput <- reactive({gsub("-","", as.character(input$beginning_date))})

end_dateInput <- reactive({gsub("-","",as.character(input$end_date))})

key_wordInput <- reactive({gsub(" ", "+", input$key_words)})  
  
renderPlot({ 
                              results.list <- suppressWarnings(readLines(sprintf("http://api.nytimes.com/svc/search/v2/articlesearch.json?fq=%s&facet_field=source&begin_date=%s&end_date=%s&api-key=%s",                                                           key_wordInput(), beginning_dateInput(), end_dateInput(), API_KEY)))
                              results <- fromJSON(results.list)
                              df <- data.frame(Headline=character(), Snippet = character(), stringsAsFactors = FALSE)
                              for (i in seq(1:length(results$response$docs))){
                                 df[i,1] <- paste(strwrap(results$response$docs[[i]]$headline[1], width = 60), collapse = "\n")
                                 df[i,2] <- paste(strwrap(results$response$docs[[i]]$snippet[1], width = 60), collapse = "\n")
                                }
                              tt <- ttheme_default(colhead=list(fg_params = list(parse=TRUE)))
                              grid.table(df, theme=tt)
                          }, width = "auto", height = 720)
```
