---
title: "Homework 12"
author: "Christophe Hunt"
date: "April 29, 2017"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
always_allow_html: yes
---

# Page 576: problem 2

Consider a company that allows back ordering. That is, the company notifies customers that a temporary stock-out exists and that their order will be filled shortly. What considerations might argue for such a policy? What effect does such a policy have on storage costs? Should costs be assigned to stock-outs? Why? How would you make such an assignment? What assumptions are implied by the model in Figure 13.7? Suppose a "loss of goodwill cost" of w dollars per unit per day is assigned to each stock-out. Compute the optimal order quantity Q* and interpret your model.

> What considerations might argue for such a policy? There are times where a product may not be popular but a vendor would like to continue to sell the product to maintain good customer relationships. The product may not sell enough to warrant storing it and the fees associated so the vendor would allow backordering to keep the business. 

> What effect does such a policy have on storage costs? The policy can limit storage fees on low demand products, it is an effective policy and offered by many vendors. It also allows the company to store more popular products. 

> Should costs be assigned to stock-outs? Why?  The costs associated with stock-outs is the "loss of goodwill costs", since the customer does not get the product immediately there is the possiblity they will not purchase or they may no longer purchase from the company. 

> How would you make such an assignment? What assumptions are implied by the model in Figure 13.7?

o = items ordered
q = quantity of items on hand 
s = storage cost per unit 
w = stock out cost per item per unit (goodwill loss)
d = deliver costs in dollars per delivery 
t = time intervals between deliveries 

Using 13.3 as a guide:

cost per cycle : $d + s\frac{q}{2}t - w$
$c = \frac{d}{t} + \frac{sq}{2} - \frac{w}{t}$

Much like 13.3 the quantity is actually the items ordered since the product is on backorder and only ordered when needed. 

cost of stock-outs : $d + s\frac{q}{2}t - w$
$c = \frac{d}{t} + \frac{sot}{2} - \frac{w}{t}$

$c = -\frac{d}{t^2} + \frac{so}{2} - \frac{w}{t^2}$

\newpage

# Page 585: problem 2

Find the local minimum value of the function

$f(x,y) = 3x^2 + 6xy + 7y^2 - 2x + 4y$

d/dx:  

$\frac{\partial}{\partial x}(3x^2 + 6xy + 7y^2 - 2x + 4y)$    
$= 3(\frac{\partial}{\partial x}(x^2)) + 6y(\frac{\partial}{\partial x}(x)) + \frac{\partial}{\partial x}(7y^2) - 2 (\frac{\partial}{\partial x}(x)) + \frac{\partial}{\partial x}(4y)$   


Derivative of x is 1:

$= 3(\frac{\partial}{\partial x}(x^2)) + 6y + \frac{\partial}{\partial x}(7y^2) - 2 + \frac{\partial}{\partial x}(4y)$   

Use the power rule, $\frac{\partial}{\partial x}(x^n) = nx^{n-1}$, where n = 2: $\frac{\partial}{\partial x} (x^2)= 2x$ and derivative of $4y$ = 0:

$= 3 (2x) + 6y + \frac{\partial}{\partial x}(7y^2) - 2$  

The derivative of $7x^2$ = 0 :

$\frac{\partial}{\partial x}(3x^2 + 6xy + 7y^2 - 2x + 47) =6x + 6y -2$   

d/dy:

$\frac{\partial}{\partial y}(3x^2 + 6xy + 7y^2 - 2x + 47)$    
$= (\frac{\partial}{\partial y}(3x^2)) + 6x(\frac{\partial}{\partial y}(y)) + 7\frac{\partial}{\partial y}(y^2) - (\frac{\partial}{\partial y}(-2x)) + 4\frac{\partial}{\partial y}(y)$   

The derivative of -2x, and $3x^2$ = 0:

$= 6x(\frac{\partial}{\partial y}(y)) + 7\frac{\partial}{\partial y}(y^2) + 4\frac{\partial}{\partial y}(y)$   

The derivative of y = 1:

$= 6x + 7\frac{\partial}{\partial y}(y^2) + 4$  

Using the power rule :

$0 = 6x + 7*2y + 4 = 6x + 14y + 4$    


Finding the local minima:    
$0 = 6x + 6y -2$   
$-6y = 6x - 2$   
$y = -x + \frac{1}{3}$   

$0 = 6x + 14y + 4$    
$-6x = 14y + 4$   
$x = -\frac{14}{6}y - \frac{4}{6}$   
$x = -\frac{14}{6}(-x + \frac{1}{3}) - \frac{4}{6}$   
$x = \frac{13}{12}$  

$y = - \frac{13}{12} + \frac{1}{3}$   

min at (x,y) = $(\frac{13}{12}, -\frac{1}{4})$   

\newpage

# Page 591: problem 5

Find the hottest point (x, y, z) along the elliptical orbit

$$4x^2 +y^2 +4z^2 = 16$$

Where the temperature function is:

$$T(x,y,z) = 8x^2 + 4yx - 16z + 600$$
Maximize $T(x,y,z) 8x^2 + 4yx - 16z + 600$ such that $4x^2 +y^2 +4z^2 = 16$. 

$L(x,y,z,\lambda) = 8x^2 + 4yx - 16z + 600 + \lambda 4x^2 + \lambda y^2 +\lambda 4z^2 -\lambda 16)$

d/dx:

$= 8 (\frac{\partial}{\partial x}(x^2)) + 4y\frac{\partial}{\partial x}(x)) + \frac{\partial}{\partial x}(- 16z) + \frac{\partial}{\partial x}(600) + 4 \lambda \frac{\partial}{\partial x}(x^2) + \frac{\partial}{\partial x}(y^2\lambda) + \frac{\partial}{\partial x} (4z^2\lambda) + \frac{\partial}{\partial x} (-16 \lambda)$

The derivatives of $600$, $-16z$, $-16 \lambda$, $\lambda y^2$, and $4 \lambda z^2$

$= 8 (\frac{\partial}{\partial x}(x^2)) + 4y\frac{\partial}{\partial x}(x) + 4 \lambda \frac{\partial}{\partial x}(x^2)$

Using the power rule:

$= 16x + 4y + 8x\lambda$

d/dy :

$= \frac{\partial}{\partial y}(8x^2) + 4x(\frac{\partial}{\partial y}(y)) + \frac{\partial}{\partial y}(-16z) + \frac{\partial}{\partial y}(600) + \frac{\partial}{\partial y}(4x^2\lambda) + \lambda ( \frac{\partial}{\partial y} (y^2)) +  \frac{\partial}{\partial y}(\lambda4z^2) + \frac{\partial}{\partial y}(-16\lambda)$

The derivative of 600, $8x^2$, -16z, $-16\lambda$, $4\lambda x^2$ and $4 \lambda z^2$:

$= 4x(\frac{\partial}{\partial y}(y))  + \lambda ( \frac{\partial}{\partial y} (y^2))$

Using the power rule:

$= 4x + 2y \lambda$

d/dz:

$\frac{\partial}{\partial z} (8x^2) + \frac{\partial}{\partial z}(4yx) + 16\frac{\partial}{\partial z}(z) + \frac{\partial}{\partial z} \frac{\partial}{\partial z} (600) + \frac{\partial}{\partial z} (4x^2 \lambda) + \frac{\partial}{\partial z} (y^2 \lambda) + 4 \lambda (\frac{\partial}{\partial z} (z^2)) + \frac{\partial}{\partial z} (-16 \lambda)$

The derivative of $600$, $8x^2$, $4xy$, $-16 \lambda$, $4 \lambda x^2$, and $\lambda y^2$ are 0:

$16\frac{\partial}{\partial z}(z) + 4 \lambda (\frac{\partial}{\partial z} (z^2))$

The derivative of x is 1 and using the power rule :

$= -16 + 8z \lambda$

-------

$0 = 16x + 4y + 8x\lambda$  
$y = -4x + 2x \lambda$  

$0 = 4x + 2y \lambda$  
$0 = 4x -8x +4x \lambda$  
$0 = -4x +4x \lambda$  
$4x = 4x \lambda$  
$\lambda = 1$  

$0 = -16 + 8z \lambda$
$0 = -16 + 8z$
$z = 2$    

$y = -2x$    

$0 = 4x + 2(-2x)$    
$0 = 0$      

$x = x, y = -2x, z = 2, \lambda = 1$   

$8x^2 + 4(-2x)x - 16(2) + 600$    
$8x^2 + (-8x^2) + 568$   

Hottest point = $568$    

# Page 599: problem 5

One of the key assumptions underlying the models developed in this section is that the harvest rate equals the growth rate for sustainable yield. The reproduction sub-models in Figures 13.19 and 13.22 suggests that if the current population levels are known, it is possible to estimate the growth rate. The implications of this knowledge is that if a quota for the season is established based on the estimated growth rate, then the fish population can be maintained, increased, or decreased as desired. This quota system might be implemented by requiring all commercial fishermen to register their catch daily and then closing the season when the quota is reached. Discuss the difficulties in determining reproduction models precise enough to be used in this manner. How would you estimate population level? What are the disadvantages of having a quota that varies from year to year? Discuss the practical political difficulties in implemented such a procedure. 

> The first difficulty is getting an accurate measure of the current population levels. There are numerous issues in that you simply cannot calculate and count every fish. The methods to count fish, while sophisicated, still are not completely accurate. Additionally, the variations among the populations can be immense, a shortage of food in one location could have reduced the population in that region making a large catch in the region unsustainable. 

> The disadvantages in having a quota change from year to year is education among fisherman. It would be difficult to ensure that fishermen understood that changing quotas and did not overfish. It also makes it difficult for fisherman to estimate the commerical value of a catch, they could be weighing the options of fishing for different species during different seasons and a changing quota would make that difficult. 

> How would you estimate population levels? I would take a sample of an area over time, measuring all possible factors that may be associated with population growth. Then I would apply the model over areas over the same time period to generate a propestice count of the population at the current level. Possible issues is localized events that have larger impacts to the population that my model may not take into account. 

> The political disadvantages is that seasons with a limited overall catch benefits the larger commerical operations and disfavors the smaller operations. The smaller operations may have more political influence in local politics and also may employ more local voters.  

