---
title: "Homework 8"
author: "Christophe Hunt"
date: "March 21, 2017"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
---

# Page 347: problem 4

We have engaged in a business venture. Assume the probability of success is $P(s) = \frac{2}{5}$; further assume that if we are successful we make \$55,000, and we are unsuccessful we lose \$1,750. Find the expected value of then business venture. 

> $9200

# Page 347: problem 6

Consider a firm handling concessions for a sporting vent. The firm's manager needs to know whether to stock up with coffee or cola and is formulation policies for specific weather predictions. A local agreement restricts the firm to selling only one type of beverage. The firm estimates a \$1,500 profit selling cola if the weather is cold and a \$5,000 profit selling cola if the weather is warm. The firm also estimates a \$4,000 profit selling coffee if it is cold and a \$1000 profit selling coffee if the weather is warm. The weather forecast says that there is a 30% of a cold front; otherwise, the weather will be warm. Build a decision tree to assist with the decision. What should the firm handling concessions do? 

# Page 355: problem 3

The financial success of a ski resort in Squaw valley is dependent on the amount of early snowfall in the fall and winter months. If the snowfall is greater than 40 inches, the resort always has a successful ski season. If the snow is between 30 and 40 inches, the resort has a moderate season, and if the snowfall is less than 30 inches, the season is poor, and the resort will lose money. The seasonal snow probabilities from the weather service are displayed in the following table with the expected revenue for the previous 10 seasons. A hotel chain has offered to lease the resort during the winter for $100,000. You must decide whether to operate yourself or lease the resort. Build a decision tree to assist in the decision.

# Page 364: problem 3

A big private oil company must decide whether to drill in the Gulf of Mexico. It costs \$1 million to drill, and if oil is found its value is estimated at \$6 million. At present, the oil company believes that there is a 45% chance that oil is present. Before drilling begins, the big private oil company can hire a geologist for \$100,000 to obtain samples and test for oil. There is only about a 60% chance that the geologist will issue a favorable report. Given that the geologist does issue a favorable report, there is an 85% chance that there is oil. Given an unfavorable report, there is a 22% chance that there is oil. Determine what the big private oil company should do. 

# Page 373: problem 1
