---
title: "R Notebook"
output: html_notebook
---

## Chapter 2 Problem 9 

Find all five of the steady-state querieing metrics for an M/D/1 queue, where D denotes a deterministic "distribution", i.e., the associated RV (in this case representing service times) is a constant with no variation at all (also called a degenerate distribution). State parameter conditions for your results to be valid; use the same meaning for $\lambda$, $\mu$, and $p$ as we did in this chapter. Compare your results to those if D were replaced by a distribution with mean equal to the constant value from the orginal D distribution, except having at least some variation. 




```{r}

```


## Chapter 4 Problem 15

Build a Simio model to confirm and cross-check the steady-state queueing-theoretic results from your solutions to the M/D/1 queue of Problem 9 in Chapter 2. Remember that your Simio model is initialized empty and idle, and that it produces results that are subject to statistical variation, so design and run a Simio Experiment to deal with both of these issues; make your own decisions about things like run length, number of replications, and Warm-Up Period, possibly after some trial and error. For each of the five steady-state queuing metrics, first compute numerical values for the queueing-theoretic steady-state output performance metrics $W_q$, $W$, $L_q$, $L$, and $p$ from your solutions to Problem 9 in Chapter 2, and then compare these with your simulation estimates and confidence intervals. All time units are in minutes, and use minutes as well throughout your Simio model. Take the arrivale rate to be $\lambda$ = 1 per minute, and the service rate to be $\mu$ = 1/.9 per minute. 




