---
title: "Final Project - Christophe"
author: "Christophe Hunt"
date: "April 23, 2016"
output: html_document
---

Need to run only this chunk (`Twitter Setup`) first because you need to but in a PIN given by Twitter.  

```{r, Twitter Setup}
library(twitteR)
library(httr)
library(ROAuth)

consumer_key <- "vPOqiiCwFT9N1iXNP24y2stmc"
consumer_secret <- "IPE1ct2pu4E633Y9OoQ35V9AeLZ1oU4UKlfNb2A0lvbwZZ2jil"
access_token <- "4228029732-Ax9gP4SArwAIxnJK0pIFVsBmHhIBFTcHbn0dsvJ"
access_secret <- "1lp8uHBeK0VTuog9wOfbtIBxXWrnKoqin6sTCUg9ogJNu"

download.file(url='http://curl.haxx.se/ca/cacert.pem', destfile='cacert.pem')
reqURL <- 'https://api.twitter.com/oauth/request_token'
accessURL <- 'https://api.twitter.com/oauth/access_token'
authURL <- 'https://api.twitter.com/oauth/authorize'

Cred <- OAuthFactory$new(consumerKey=consumer_key,
                         consumerSecret=consumer_secret,
                         requestURL=reqURL,
                         accessURL=accessURL,
                         authURL=authURL)

Cred$handshake(cainfo = system.file('CurlSSL', 
                                    'cacert.pem', 
                                    package = 'RCurl'))
```

Run the following chunks after entering the PIN for Twitter Authorization.

```{r}
save(Cred, file='twitter authentication.Rdata')
load('twitter authentication.Rdata') 
setup_twitter_oauth(consumer_key, 
                    consumer_secret, 
                    access_token, 
                    access_secret)
```

This chunk gets the twitter search results for a term, `searchTwitter` has some other settings that could probably improve results.

```{r, Searching Twitter}
search_term <- function(term){
  require(magrittr)
  search_term <- gsub(" ", "+", term) %>%
                 paste("+movie", sep = "")
  return(search_term)
}
 
SearchTerm <- search_term("barbershop")
list <- searchTwitter(SearchTerm, geocode='40.730610,-73.935242,1000mi', since = '2016-05-02', until = '2016-05-03') #TODO find major cities, 10 major
df <- twListToDF(list)

```



```{r}
library(magrittr)
library(tm)

rm_special <-function(x) iconv(x, "UTF-8", "UTF-8",sub='')


corpus  <- Corpus(VectorSource(df$text))                %>%
           tm_map(rm_special)                           %>%
           tm_map(removePunctuation)                    %>%
           tm_map(tolower)                              %>%
           tm_map(removeNumbers)                        %>%
           tm_map(removeWords, stopwords("english"))  

library(h2o)
library(qdap)
                       
polarity(
  sentSplit(df$text, stem.col = TRUE)
         , grouping.var = NULL,
polarity.frame = qdapDictionaries::key.pol, constrain = FALSE,
negators = qdapDictionaries::negation.words,
amplifiers = qdapDictionaries::amplification.words,
deamplifiers = qdapDictionaries::deamplification.words,
question.weight = 0, amplifier.weight = 0.8, n.before = 4,
n.after = 2, rm.incomplete = FALSE, digits = 3)

```

```{r}
x <- as.data.frame(unlist(sentiment(rm_special(unique(df$text)),  api_key = '114ffc17022fd58af3da5cfd5f3e4388')))
x <- cbind(x,unique(df$text))

x <- c("An exhilarating hybrid of Social Realism and feel-good aspirational entertainment, Paddy Breathnach's "Viva" is an oddity by its very pedigree: an Irish movie set in Havana, where it was filmed with a keen eye to that city's dinginess in tropical light. It infuses a too-familiar story with so much heart that you surrender to its charm and forgive it for being unabashedly formulaic. Even its one big plot twist is hardly a surprise. At the same time, its portrait of Havana, an impoverished city of crumbling architecture, has a gritty neorealist pungency.

Its hero, Jesus (Héctor Medina), is a gay hairdresser who dreams of becoming a drag entertainer at the nightclub where he coifs the noisy, squabbling divas. To make ends meet, this slim, handsome young man with plucked eyebrows moonlights as a hustler along with his friends. The one brief clip that shows him having sex with a client makes clear that it is grueling, humiliating work.

Jesus, whose mother is dead and whose father abandoned him, lives in a slum, and is watched over by the club's tough but caring star, an aging drag queen known as Mama (Luis Alberto García). Complicating Jesus's precarious existence is the sudden reappearance of his father, Angel (Jorge Perugorría), a former boxer released from prison who likes his rum and is rumored to have killed a man. Angel's initial reaction to his son's homosexuality and fondness for drag is all too predictable: He punches him in the face.

Unlike other macho father-gay son dramas, "Viva" doesn't amplify Angel's hostility to tell a prolonged tale of persecution and liberation. That spasm of violence is more a reflex than an expression of deep hatred.

Angel, who is falling apart physically, is filled with regret about how he has led his life. Without asking, he moves in with Jesus and adopts an attitude of paternal authority. But his machismo is more pathetic than threatening. Instead of cowering before his father, Jesus stands up for himself. Sweet-natured, he is helpful and nurturing and they form a edgy bond.

Mark O'Halloran's screenplay humanizes the characters to the degree that their relationships assume a dimension well beyond the shallow stereotypes often found in fraught dramas about sexuality and family conflict. Mr. Perugorría's Angel, for instance, is a sad wreck of a man who has lived by a code that has begun to fail him. He doesn't know any other way to be than to put on a brave front.

Luis Alberto García's portrayal of Mama, who offers to shelter Angel, if necessary, infuses new life into the stereotype of the tough drag-queen survivor.

Best of all is Mr. Medina's lovable Jesus, who is androgynous without the usual clichéd drag-queen mannerisms. Viva is his stage name. He is also a terrific dancer who, given the chance to perform, displays the charisma of a natural star.")

sentiment(rm_special(x),  api_key = '114ffc17022fd58af3da5cfd5f3e4388')
```

```{r}
library(httr)
library(RCurl)
alchemy_url <- "http://access.alchemyapi.com/calls/url/"
api_feature <- "URLGetTextSentiment"
the_url <- "https://dreamtolearn.com/node/8OVIWY2C5RLZZSYD9OHCKM8AI/80"
api_key <- "dbd2420ad27fb76303d57fbb2c7d9de7e7b0950c"  # alchemy API secret key 

temp <- paste(alchemy_url,api_feature,"?url=",the_url,"&apikey=",api_key,"&outputMode=json", sep="")
temp
POST(temp)
```