---
title: "Week 7 - Chapter 5"
output: html_notebook
---

Problem #6

In Model 5-2, we assumed that the inspection workers did not overlap between shifts. Modify the model so that the inspectors do overlap for the first hour of one shift and the last hour of the other shift. Compare the results of the two models. Does having the inspectors overlap help?


Problem #7

In the description of Model 5-2, we noted that there is no limit on the number of times that a board may be found in need of rework. Modify Model 5-2 so that if a board fails the inspection more than two times, it is rejected as a bad part. Count the number of boards that are rejected because of 3 or more failures. 

> I originally set up the Model to include the rejection at 3 failed attempts at processing. I changed the parameters back to a simple model without limits on rejection.


Problem #8 

In the description of Model 5-3, we indicated that as part of our model verification, we had predicated the proportions of parts that would go to the fast, medium and slow fine-pitch placement machines (38%, 33%, and 29%, respectively). Develop a queuing model to estimate these proportions. 

>Unfortunately, Simio did not want to route the entities via the node to multiple stations. Unable to verify results. 

Problem #9

See book for description of problem. 

> I ran into a challenge in establishing different inter-arrival times for different processes. Below is the model set up and I appreciate any feedback on how to establish the different inter-arrival times for the different processes with a proporational split. 





