---
title: "Homework 4"
author: "Christophe Hunt"
date: "February 20, 2017"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
---

In this problem, we'll verify using R that SVD and Eigenvalues are related as worked out in the weekly module. Given a 3 × 2 matrix A


\[
A = \begin{bmatrix}
    1 & 2 & 3 &4  \\
   -1 & 0 & 1 & 3  \\
   0 & 1 & -2 & 1   \\
   5 & 4 & -2 & -3   \\
\end{bmatrix}
\]

A =

1 2 3
???1 0 4
(1)
write code in R to compute X = AAT and Y = ATA. Then, compute the eigenvalues
and eigenvectors of X and Y using the built-in commans in R.
Then, compute the left-singular, singular values, and right-singular vectors of A using
the svd command. Examine the two sets of singular vectors and show that they are indeed
eigenvectors of X and Y. In addition, the two non-zero eigenvalues (the 3rd value will
be very close to zero, if not zero) of both X and Y are the same and are squares of the
non-zero singular values of A.
Your code should compute all these vectors and scalars and store them in variables.
Please add enough comments in your code to show me how to interpret your steps.
