---
title: "Homework 2"
author: "Christophe Hunt"
date: "February 8, 2017"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
---

# Page 69: problem 12    
 
From this vague scenario, identify a problem you would like to study. Which variables affect the behavior you have identified in the problem identification? Which variables are the most important? 

A company with a fleet of trucks faces increasing maintenance costs as the age and mileage of the trucks increase.

A problem that would be interesting to study is the at what point should the truck be retired and a new vehicle purchased. The costs associated with a new purchase would need to outweight the cost of maintaining the aged truck. The variables of importance would be the maintenance cost as its associted with the age and milage of the truck, any additional variables such as the severity of past repairs. I would assume that a vehicle with engine failure may have future issues until the engine is replaced, at which point the cost of maintenance may not be as severe. Additionally, the cost of a new purchase would be the continuing payments, depreciation, maintenance, fuel effecieny, and the opportunity costs of reliability. The equilibrium of this system would be meaningful to make a data driven decision to buy a new vehicle or to keep running the aged truck. 
 
# Page 79: problem 11    

Determine whether the data set supports the stated proportionality model 
 
$$y \propto x^3$$
\begin{table}[!htbp]
\centering
\caption{}
\label{my-label}
\begin{tabular}{l|llllllllll}
y & 4 & 11 & 22 & 35 & 56 & 80 & 107 & 140 & 175 & 215 \\ \hline
x & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10
\end{tabular}
\end{table}

# Page 94: problem 4    

Lumber Cutters - Lumber cutters wish to use readily available measurements to estimate the number of board feet for lumber in a tree. Assume they measure the diameter of the tree in inches at waist height. Develop a model that predicts board feet as a function of diameter in inches. 

Use the following data for your test.

\begin{table}[!htbp]
\centering
\caption{}
\label{my-label}
\begin{tabular}{l|llllllllll}
x & 17 & 19 & 20 & 23 & 25 & 28 & 32 & 38 & 39 & 41 \\ \hline
y & 19 & 25 & 32 & 57 & 71 & 113 & 123 & 252 & 259 & 294
\end{tabular}
\end{table}

The variable $x$ is the diameter of a ponderous pine in inches, and y is the number of board feet divided by 10. 

a. Consider two separate assumptions, allowing each to lead to a model. Completely analyze each model.
  i. Assume that all trees are right-circular cylinders and are approximately the same height.
  ii. Assume that all trees are right-circular cylinders and that the height of the tree is proportional to the diameter.
b. Which model appears to be better? Why? Justify your conclusions. 
 
# Page 99: problem 3    

Discuss several factors that were completely ignored in our analysis of the gasoline mileage problem. 
 
# Page 104: problem 2

Tests exist to measure the percentage of body fat. Assume that such tests are accurate and that a great many carefully collected data are available. You may specify any other statistic, such as waist size and height, that you would like collected. Explain how the data could be arranged to check the assumptions underlying the sub models in this section. For example, suppose the data for males between ages 17 and 21 with constant body fat and height are examined. Explain how the assumption of constant density of the inner core could be checked. 
