---
title: "CHunt_Assignment2_PS1_PS2"
author: "Christophe Hunt"
date: "February 8, 2017"
output: pdf_document
---

## Problem Set 1 

1. Show that $A^TA\neq AA^T$ in general. (Proof and demonstration.)
2. For a special type of square matrix A, we get $A^TA\neq AA^T$. Under what conditions could this be true? (Hint: The Identity matrix I is an example of such a matrix).

Please typeset your response using LaTeX mode in RStudio. If you do it in paper, please either scan or take a picture of the work and submit it. Please ensure that your image is legible and that your submissions are named using your first initial, last name, assignment and problem set within the assignment. E.g. LFulton_Assignment2_PS1.png

#For Reference Only
> For any matrix, we can define a special operation called the transpose. Given a matrix A, we define its transpose, AT as a matrix whose rows are the columns of A and vice versa. So, if A is m × n, AT is n × m. When you have two vectors x and y, we can consider them as essentially two n × 1 matrices. From this perspective, the dot-product between x and y is simply a matrix multiplication between x T and y. x Tis 1 × n and y is n × 1 producing a 1 × 1 product. Therefore x · y is also be written as x T y.


## Problem Set 2 
Matrix factorization is a very important problem. There are supercomputers built just to do matrix factorizations. Every second you are on an airplane, matrices are being factorized. Radars that track flights use a technique called Kalman filtering. At the heart of Kalman Filtering is a Matrix Factorization operation. Kalman Filters are solving linear systems of equations when they track your flight using radars. Write an R function to factorize a square matrix A into LU or LDU, whichever you prefer. Please submit your response in an R Markdown document using our class naming convention, E.g. LFulton_Assignment2_PS2.png You don't have to worry about permuting rows of A and you can assume that A is less than 5x5, if you need to hard-code any variables in your code. If you doing the entire assignment in R, then please submit only one markdown document for both the problems.


