---
title: "Homework 10"
author: "Christophe Hunt"
date: "April 3, 2017"
output: pdf_document
---

# 1. Problem Set

Playing with PageRank You'll verify for yourself that PageRank works by performing calculations on a small universe of web pages. Let's use the 6 page universe that we had in the course notes.

For this directed graph, perform the following calculations in $R$.

## 1 
Form the A matrix. Then, introduce decay and form the $B$ matrix as we did in the course notes.

## 2 
Start with a uniform rank vector r and perform power iterations on B till convergence. That is, compute the solution $r = B^n x r$. Attempt this for a sufficiently large $n$ so that $r$ actually converges.

## 3 
Compute the eigen-decomposition of $B$ and verify that you indeed get an eigenvalue of 1 as the largest eigenvalue and that its corresponding eigenvector is the same vector that you obtained in the previous power iteration method. Further, this eigenvector has all positive entries and it sums to 1.

## 4

```{r, warning=FALSE, message=FALSE}
library(graph)
```

Use the $graph$ package in R and its $page.rank$ method to compute the Page Rank of the graph as given in A. Note that you don't need to apply decay. The package starts with a connected graph and applies decay internally. Verify that you do get the same PageRank vector as the two approaches above. Please document all your experiments in an R Markdown document.
