---
title: "R Notebook"
output: html_notebook
---

Kelton Chapter 6 problems 1, 2, 3, 4, 5, 8

1. Use file from text to fit one or more probability distributions, including goodness-of-fit testing and probability plots. What's the recommendtation for a dtirbution to be used in the simuatlion model from which to generate these interarrival times? PRovide the correct Simio expression, heading any parameterization-difference issues.

2. Use file from text to fit one or more probability distributions, including goodness-of-fit testing and probability plots. What's the recommendtation for a dtirbution to be used in the simuatlion model from which to generate these call-duration times? PRovide the correct Simio expression, heading any parameterization-difference issues.

3. Use file from text to fit one or more probability distributions, including goodness-of-fit testing and probability plots. What's the recommendtation for a dtirbution to be used in the simuatlion model from which to generate the number of extra tech-support people need for a call? PRovide the correct Simio expression, heading any parameterization-difference issues.

4. Dervie the inverse-CDF formula for geneation random variats from a continuous uniform distribution between real numbers a and b (a < b )

5. Dervie the inverse-CDF fomula for generation random variates from a Weibull distribution. Look up its definition (including its CDF) in one of the refreences, either book or online, cited in this chapter. Check the simio definition in its documetation to be sure you have your formula parameterized proper. 

8. Problem in text:

