---
title: "Homework 12"
author: "Christophe Hunt"
date: "April 22, 2017"
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
always_allow_html: yes
---

\newpage

# Page 529: problem 1

Verify that the given function pair is a solution to the first-order system. 

$x = -e^t$, $y = e^t$       
$\frac{dx}{dt} = -y$, $\frac{dy}{dt} = -x$      

$\frac{dx}{dt} = \frac{d}{dt}(-e^t) = e^t = y$ ; $\frac{dx}{dt} = -y$   

$\frac{dy}{dt} = \frac{d}{dt}(e^t) = -e^t = x$ ; $\frac{dy}{dt} = -x$   

# Page 529: problem 6

Find and classify the rest points of the given autonomous system. 

$\frac{dx}{dt} = -(y-1)$, $\frac{dy}{dt} = x-2$

The rest point of the system is a point in the phase plane for which $f(x,y) = 0 and g(x,y) = 0$, then both the derivatives $\frac{dx}{dt} = 0$ and $\frac{dy}{dt}= 0$. 

when $y = 1$, $\frac{dx}{dt} = -(1-1)$; $\frac{dx}{dt}= 0$    
when $x = 2$, $\frac{dy}{dt} = 2 - 2$; $\frac{dy}{dt} = 0$   

$(2,1)$ is the rest point of the autonomous system $\frac{dx}{dt} = -(y-1)$, $\frac{dy}{dt} = x-2$   

# Page 546: problem 1

Apply the first and second derivative tests to the function 
$f(y) = y^a/e^{by}$ to show that $f(y) = y^a/e^{by}$ is a unique critical point that yields the relative maximum $f(a/b)$. Show also that $f(y)$ approaches zero as y tends to infinity. 

first derivative:

$\frac{df(y)}{dy} = 0$    
$\frac{d(\frac{y^a}{e^{by}})}{dy} = 0$    

Use the product rule:
$= y^{a}(\frac{d}{dy}(e^{-by})) + e^{-by}(\frac{d}{dy}(y^{a}))$
 
Use the chain rule:
$= \frac{\frac{d}{dy}(y^a)}{e^{by}}+\frac{\frac{d}{dy}-(by)}{e^{by}} y^a$     
Factor out constants:
$= \frac{\frac{d}{dy}(y^a)}{e^{by}} + \frac{-b\frac{d}{dy}(y)}{e^{by}}y^a$  
The derivative of y is 1:
$= \frac{\frac{d}{dy}y^a}{e^{by}}-\frac{1 b y^a}{e^by}$  
 
Use the power rule: 
$= \frac{-b y^a}{e^{by}} + \frac{a y^{a-1}}{e^{by}}$    

Answer: $y^{a-1}e^{-by}(a-by)=0$   

Since $e^{by}$ cannot be zero :

$y = \frac{a}{b}~or~y =0$

Second derivative

$\frac{d^2f(y)}{dy^2} = \frac{d\frac{ay^{a-1}-y^ab}{e^{by}}}{dy}$    
$\frac{d^2f(y)}{dy^2} = \frac{e^{by}\{a(a-1)y^{a-2}-ay{a-1}\}-(ay^{a-1}-y^a)be^{by}}{e^{2by}}$

Substitute the value of 0 :

$\frac{d^2f(y)}{dy^2} = 0$

Substitute the value of $y=\frac{a}{b}$

$\frac{d^2f(y)}{dy^2} = \frac{(\frac{a}{b})^{a-2}x-a}{e^a}$

As $a$ and $b$ are positive, the second derivative is less than zero and therefore it is proved that $y=\frac{a}{b}$ yields the relative maximum.

