---
title: "Week_4_Math"
author: "Christophe"
date: "July 22, 2015"
output: html_document
---


#####1. Using matrix operations, describe the solutions for the following family of equations:

      x + 2y - 3z = 5
      2x + y - 3z = 13
      -x + y = -8
      
$\textbf{} \begin{bmatrix} 1 & 2 & -3 \\ 2 & 1 & -3 \\ -1 & 1 & 0 \end{bmatrix}\,\,$
$\textbf{} \begin{bmatrix} x \\ y \\ z \end{bmatrix}\,\,$ = 
$\textbf{} \begin{bmatrix} 5 \\ 13 \\ -8 \end{bmatrix}\,$

-----

$$\mathbf{(R2 < R2 - R1)} = \left[\begin{array}
{rrr}
1	& 2	& -3 &	|	& 5 \\
1	& -1 &	0 &	| &	8 \\
-1 &	1 &	0 & |  &	-8
\end{array}\right]
$$

$$\mathbf{(R3 < R3 + R2)} = \left[\begin{array}
{rrr}
1 &	2 &	-3 & | &	5 \\
1 &	-1 &	0	& |	& 8 \\
0	& 0 &	0 & | &	0
\end{array}\right]
$$

$$\mathbf{(R2 < R2 - R1)} = \left[\begin{array}
{rrr}
1 &	2 &	-3	& | &	5\\
0	& -3 &	3	& | &	3\\
0 & 	0 & 	0 & | &	0
\end{array}\right]
$$

$$\mathbf{(R2 < R2/(-3))} = \left[\begin{array}
{rrr}
1 & 	2	& -3 & | &	5\\
0	& 1 &	-1 & | &	-1\\
0	& 0 &	0 & | &	0
\end{array}\right]
$$

$$\mathbf{(R1 < R1 - R2*2)} = \left[\begin{array}
{rrr}				
1 &	0 &	-1 & | & 7\\
0	& 1 & -1 & | & -1\\
0	& 0 &	0 &| &		0
\end{array}\right]
$$

**x - z = 7**	== **x = z + 7**	

---

**y - z = -1** == **y = z - 1**

---

**Solution (x =  z + 7, y = z - 1)**

---
   
##### 2. Provide a solution for #1, using R functions of your choice.

```{r, echo = FALSE}
suppressWarnings(suppressMessages(library(editrules)))
```

```{r}
M_data <- c(1,2,-1,2,1,1,-3,-3,0,5,13,-8)
M <- matrix(M_data, nrow = 3, ncol = 4)
M

Matrix <- editrules::echelon(M)
Matrix
Results_1 <- paste(Matrix[1,1], "y + ", Matrix[1,2], "x + ", Matrix[1,3], "z = ", Matrix[1,4])
Results_2 <- paste(Matrix[2,1], "y + ", Matrix[2,2], "x + ", Matrix[2,3], "z = ", Matrix[2,4])
Results_3 <- paste(Matrix[3,1], "y + ", Matrix[3,2], "x + ", Matrix[3,3], "z = ", Matrix[3,4])
```
```{r}
Results_1
Results_2
Results_3
```
---

#####3. Solve for AB by hand:

$$\mathbf{A} = \left[\begin{array}
{rrr}
4&-3\\
-3&5\\
0&1
\end{array}\right]
$$

$$\mathbf{B} = \left[\begin{array}
{rrr}
1&4\\
3&-2
\end{array}\right]
$$


$$\mathbf{X} = \left[\begin{array}
{rrr}
(4*1 + -3*3)& (4*4 + -3*-2)		\\
(-3*1 + 5*3) &	(-3*4 + 5*-2) \\
(0*1 + 1*3) &	(0*4 + 1 * -2)
\end{array}\right]
$$

$$\mathbf{X} = \left[\begin{array}
{rrr}
-5 & 22		\\
12 &	-22 \\
3 &	-2
\end{array}\right]
$$
		

#####4. Solve AB from #3 using R functions of your choice.

```{r}

A_data <- c(4,-3,0,-3,5,1)
A <- matrix(A_data, nrow = 3, ncol = 2)
A

B_data <- c(1,3,4,-2)
B <- matrix(B_data, nrow = 2, ncol = 2)
B

A %*% B

```


