\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Homework 5},
            pdfauthor={Christophe Hunt},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\ImportTok}[1]{{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{{#1}}}}
\newcommand{\BuiltInTok}[1]{{#1}}
\newcommand{\ExtensionTok}[1]{{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Homework 5}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{Christophe Hunt}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \predate{\centering\large\emph}
  \postdate{\par}
  \date{March 4, 2017}

\usepackage{relsize}
\usepackage{setspace}
\usepackage{amsmath,amsfonts,amsthm}
\usepackage[sfdefault]{roboto}
\usepackage[T1]{fontenc}
\usepackage{float}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Problem Set 1}\label{problem-set-1}

Consider the unsolvable system Ax = b as given below: \[
\begin{bmatrix}
    1 & 0  \\
    1 & 1 \\
    1 & 3 \\
    1 & 4 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
\end{bmatrix}
=
\begin{bmatrix}
0 \\
8 \\
8 \\
20  \\
\end{bmatrix}
\]

\subsection{\texorpdfstring{Write R Markdown script to compute \(A^TA\)
and
\(A^Tb\)}{Write R Markdown script to compute A\^{}TA and A\^{}Tb}}\label{write-r-markdown-script-to-compute-ata-and-atb}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{A <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{), }\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{)}
\NormalTok{b <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{20}\NormalTok{))}

\NormalTok{ATA <-}\StringTok{ }\KeywordTok{t}\NormalTok{(A) %*%}\StringTok{ }\NormalTok{A}
\NormalTok{ATb <-}\StringTok{ }\KeywordTok{t}\NormalTok{(A) %*%}\StringTok{ }\NormalTok{b}

\NormalTok{results <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\StringTok{"ATA"} \NormalTok{=}\StringTok{ }\NormalTok{ATA, }\StringTok{"ATb"} \NormalTok{=}\StringTok{ }\NormalTok{ATb)}
\NormalTok{results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $ATA
##      [,1] [,2]
## [1,]    4    8
## [2,]    8   26
## 
## $ATb
##      [,1]
## [1,]   36
## [2,]  112
\end{verbatim}

\subsection{\texorpdfstring{Solve for \(\hat{x}\) in R using the above
computed
matrices}{Solve for \textbackslash{}hat\{x\} in R using the above computed matrices}}\label{solve-for-hatx-in-r-using-the-above-computed-matrices}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\KeywordTok{solve}\NormalTok{(ATA) %*%}\StringTok{ }\NormalTok{ATb}
\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1]
## [1,]    1
## [2,]    4
\end{verbatim}

\subsection{What is the squared error of this
solution?}\label{what-is-the-squared-error-of-this-solution}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p <-}\StringTok{ }\NormalTok{A %*%}\StringTok{ }\NormalTok{x}
\CommentTok{#b = p + e or e = p - b which we can substitute in our given values. }
\NormalTok{e <-}\StringTok{ }\NormalTok{p -}\StringTok{ }\NormalTok{b}
\CommentTok{# we then sum the square of errors. }
\NormalTok{e2 <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(e^}\DecValTok{2}\NormalTok{)}
\NormalTok{e2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 44
\end{verbatim}

\subsection{Find the exact solution with p instead of
b}\label{find-the-exact-solution-with-p-instead-of-b}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{options}\NormalTok{(}\DataTypeTok{scipen =} \DecValTok{999}\NormalTok{)}
\NormalTok{p   <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{13}\NormalTok{,}\DecValTok{17}\NormalTok{))}
\NormalTok{ATp <-}\StringTok{ }\KeywordTok{t}\NormalTok{(A) %*%}\StringTok{ }\NormalTok{p}
\NormalTok{xp  <-}\StringTok{ }\KeywordTok{solve}\NormalTok{(ATA) %*%}\StringTok{ }\NormalTok{ATp}
\NormalTok{p2  <-}\StringTok{ }\NormalTok{A %*%}\StringTok{ }\NormalTok{xp}
\NormalTok{e   <-}\StringTok{ }\NormalTok{p2-p}
\NormalTok{e}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                          [,1]
## [1,] 0.0000000000000000000000
## [2,] 0.0000000000000008881784
## [3,] 0.0000000000000035527137
## [4,] 0.0000000000000035527137
\end{verbatim}

Essentially, the error vector e is = 0.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{e2p <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(e^}\DecValTok{2}\NormalTok{)}
\NormalTok{e2p}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.00000000000000000000000000002603241
\end{verbatim}

Show that the error \(e = b - p = [-1;3;-5;3]\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{b -}\StringTok{ }\NormalTok{p}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1]
## [1,]   -1
## [2,]    3
## [3,]   -5
## [4,]    3
\end{verbatim}

Show that the error \(e\) is orthogonal to \(p\) and to each of the
columns of \(A\).

As per the week 5 handout - We know that when two vectors are
orthogonal, their dot product is zero.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{e*p}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                         [,1]
## [1,] 0.000000000000000000000
## [2,] 0.000000000000004440892
## [3,] 0.000000000000046185278
## [4,] 0.000000000000060396133
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(e*A[,}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.000000000000007993606
\end{verbatim}

\newpage

\section{Problem Set 2}\label{problem-set-2}

Write an R markdown script that takes in the auto-mpg data, extracts an
A matrix from the first 4 columns and b vector from the fifth (mpg)
column.

Apparently, an added column of 1 is necessary to obtain an intercept.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{read.table}\NormalTok{(}\StringTok{"https://raw.githubusercontent.com/ChristopheHunt/MSDA---Coursework/master/Data%20605/Assignment%205/auto-mpg.data"}\NormalTok{))}

\NormalTok{A <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(x[,}\DecValTok{1}\NormalTok{:}\DecValTok{4}\NormalTok{],}\DecValTok{1}\NormalTok{))}
\NormalTok{b <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(x[,}\DecValTok{5}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

Using the least squares approach, your code should compute the best
fitting solution

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ATA <-}\StringTok{ }\KeywordTok{t}\NormalTok{(A) %*%}\StringTok{ }\NormalTok{A}
\NormalTok{ATb <-}\StringTok{ }\KeywordTok{t}\NormalTok{(A) %*%}\StringTok{ }\NormalTok{b}
\NormalTok{results <-}\StringTok{ }\KeywordTok{list}\NormalTok{(}\StringTok{"ATA"} \NormalTok{=}\StringTok{ }\NormalTok{ATA, }\StringTok{"ATb"} \NormalTok{=}\StringTok{ }\NormalTok{ATb)}
\NormalTok{results}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $ATA
##             V1          V2         V3         V4          
## V1  19097634.2   9374647.0  259345480  1123011.9   76209.5
## V2   9374647.0   4857524.0  132989885   607832.3   40952.0
## V3 259345480.0 132989885.0 3757575489 17758103.6 1167213.0
## V4   1123011.9    607832.3   17758104    97656.9    6092.2
##        76209.5     40952.0    1167213     6092.2     392.0
## 
## $ATb
##          [,1]
## V1  1529685.9
## V2   868718.8
## V3 25209061.4
## V4   146401.4
##        9190.8
\end{verbatim}

\newpage

\subsection{\texorpdfstring{Solve for \(\hat{x}\) in R using the above
computed
matrices}{Solve for \textbackslash{}hat\{x\} in R using the above computed matrices}}\label{solve-for-hatx-in-r-using-the-above-computed-matrices-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x <-}\StringTok{ }\KeywordTok{solve}\NormalTok{(ATA) %*%}\StringTok{ }\NormalTok{ATb}
\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            [,1]
## V1 -0.006000871
## V2 -0.043607731
## V3 -0.005280508
## V4 -0.023147999
##    45.251139699
\end{verbatim}

The least squares model using this method is:

\[mpg = -0.006*displacement + -0.04361*horsepower + -0.00528*weight + -0.02315*acceleration 
 + 45.25114\]

Finally, calculate the fitting error between the predicted mpg of youur
model and actual mpg.

\subsection{The fitting error to the predicted mpg and the actual
mpg.}\label{the-fitting-error-to-the-predicted-mpg-and-the-actual-mpg.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p <-}\StringTok{ }\NormalTok{A %*%}\StringTok{ }\NormalTok{x}
\CommentTok{#b = p + e or e = p - b which we can substitute in our given values. }
\NormalTok{e <-}\StringTok{ }\NormalTok{p -}\StringTok{ }\NormalTok{b}
\NormalTok{e}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                [,1]
##   [1,]   0.95919198
##   [2,]   1.18844197
##   [3,]   0.40325031
##   [4,]   2.47995603
##   [5,]   1.87826895
##   [6,]  -4.11172901
##   [7,]  -4.26661947
##   [8,]  -3.73121329
##   [9,]  -4.88872305
##  [10,]  -0.90138187
##  [11,]   1.49356259
##  [12,]   2.99106999
##  [13,]   1.22973585
##  [14,]   2.18187690
##  [15,]   3.55772236
##  [16,]   2.60176023
##  [17,]   6.82009386
##  [18,]   5.31326672
##  [19,]   2.24844730
##  [20,]   6.49883380
##  [21,]   1.28256448
##  [22,]   3.51707079
##  [23,]   2.53801867
##  [24,]   1.51135631
##  [25,]   4.80226596
##  [26,]  -0.97845147
##  [27,]   1.23260402
##  [28,]  -0.26644392
##  [29,]   0.59498197
##  [30,]   2.24844730
##  [31,]   0.17245834
##  [32,]   3.34126348
##  [33,]   6.28838301
##  [34,]   4.80367168
##  [35,]   4.45254442
##  [36,]   3.11841090
##  [37,]   3.77706091
##  [38,]  -0.54787405
##  [39,]  -2.61895040
##  [40,]   0.22512378
##  [41,]   0.87181916
##  [42,]  -3.32770358
##  [43,]  -2.90158894
##  [44,]  -5.20014767
##  [45,]   4.95270250
##  [46,]   6.11598637
##  [47,]   2.71230228
##  [48,]   5.00228167
##  [49,]   5.72196928
##  [50,]   1.09575284
##  [51,]   0.32137057
##  [52,]   0.16898091
##  [53,]   1.18842304
##  [54,]  -2.12397951
##  [55,]   4.92832807
##  [56,]   4.85459255
##  [57,]   4.04251609
##  [58,]   4.55756074
##  [59,]   6.86799519
##  [60,]   7.31947322
##  [61,]   7.63241624
##  [62,]   0.10889294
##  [63,]  -2.21336428
##  [64,]  -0.34569464
##  [65,]   0.36871047
##  [66,]   0.22948866
##  [67,]  -2.11286260
##  [68,]  -0.69370753
##  [69,]   0.33115718
##  [70,]  -2.07443304
##  [71,]   8.98504767
##  [72,]   1.04462895
##  [73,]   2.77627435
##  [74,]   1.28892587
##  [75,]   0.94900081
##  [76,]   5.81759309
##  [77,]   5.53482769
##  [78,]   3.55514388
##  [79,]   3.69042710
##  [80,]   5.75158442
##  [81,]   0.18182614
##  [82,]   3.73248675
##  [83,]   1.40019701
##  [84,]   2.36056653
##  [85,]   0.56847599
##  [86,]   3.22948866
##  [87,]   2.46812479
##  [88,]   1.78515902
##  [89,]   1.56787515
##  [90,]  -4.37284127
##  [91,]  -0.54033113
##  [92,]  -0.08496701
##  [93,]   0.09254556
##  [94,]  -5.02273809
##  [95,]  -5.68941815
##  [96,]   2.02802495
##  [97,]   4.45972516
##  [98,]   5.66398032
##  [99,]   5.57670109
## [100,]   5.57908559
## [101,]   1.21527018
## [102,]   5.88000140
## [103,]  -1.40113778
## [104,]  -2.62722100
## [105,]  -2.19889539
## [106,]  -0.74491128
## [107,]   6.42360830
## [108,]   8.35748564
## [109,]   7.14137593
## [110,]   5.55964889
## [111,]  11.37808640
## [112,]   9.18616531
## [113,]   5.27749023
## [114,]   2.41921441
## [115,]  -0.02824295
## [116,]  -5.98890515
## [117,]   3.39620761
## [118,]   5.53032903
## [119,]   6.64039377
## [120,]   5.13767810
## [121,]   3.59862910
## [122,]   1.35796118
## [123,]   3.85997728
## [124,]   4.69903473
## [125,]   3.15815563
## [126,]   4.80904343
## [127,]   6.38085886
## [128,]   0.11855073
## [129,]   1.70594837
## [130,]  -0.19054495
## [131,]   2.32387113
## [132,]   3.03103289
## [133,]   3.31059628
## [134,]   1.86171532
## [135,]  -0.85686044
## [136,]  -1.53907691
## [137,]  -1.04601815
## [138,]  -1.52756882
## [139,]   0.04779960
## [140,]  -0.05577611
## [141,]   5.13092213
## [142,]   2.78683828
## [143,]   2.43797215
## [144,]  -0.92367328
## [145,]   1.88375643
## [146,]   5.95037707
## [147,]   3.10036634
## [148,]   2.81068139
## [149,]   1.56303853
## [150,]  -0.07603066
## [151,]   3.15226385
## [152,]   2.53646575
## [153,]   7.00235458
## [154,]   8.48393572
## [155,]  -5.47813534
## [156,]  -1.94181274
## [157,]  -3.28566697
## [158,]  -2.21293299
## [159,]   0.95103615
## [160,]   2.16573333
## [161,]   3.76995852
## [162,]   1.33167529
## [163,]   1.67340492
## [164,]   1.56104750
## [165,]   7.80177417
## [166,]   0.56412498
## [167,]   3.46280003
## [168,]   3.74039683
## [169,]   3.89430055
## [170,]   1.68025076
## [171,]   4.49440159
## [172,]   2.47467782
## [173,]   5.90235961
## [174,]   2.10610455
## [175,]   3.58501532
## [176,]   2.84539710
## [177,]   1.68557732
## [178,]   2.36473523
## [179,]   0.09341094
## [180,]  -0.48975078
## [181,]  -0.51118356
## [182,]   3.90888396
## [183,]   1.47273527
## [184,]   2.90077893
## [185,]   2.04376751
## [186,]  -2.74247263
## [187,]  -1.62454857
## [188,]   1.45081813
## [189,]  -0.53717587
## [190,]   0.11180974
## [191,]  -0.86907843
## [192,]   0.20644503
## [193,]   0.73647051
## [194,]   2.21374471
## [195,]   5.60800083
## [196,]   2.10147495
## [197,]  -0.48743598
## [198,]  -0.14868292
## [199,]   2.99087609
## [200,]   0.83162304
## [201,]   4.78748476
## [202,]   2.15357400
## [203,]  -1.21320200
## [204,]   1.63935390
## [205,]   0.91194585
## [206,]   3.02601477
## [207,]   2.69094878
## [208,]   3.91935318
## [209,]   4.77468705
## [210,]   1.95195429
## [211,]  -4.60727165
## [212,]   2.13747876
## [213,]   3.98708648
## [214,]   3.64932432
## [215,]  -1.02914779
## [216,]  -0.62566015
## [217,]  -3.81965702
## [218,]   2.32872935
## [219,]  -2.47094955
## [220,]  -1.17996718
## [221,]   0.01538920
## [222,]  -0.65868813
## [223,]  -0.25481453
## [224,]   2.48705692
## [225,]   0.30918636
## [226,]   0.96220775
## [227,]   1.92376235
## [228,]  -3.53928595
## [229,]  -2.01968157
## [230,]  -4.05527938
## [231,]  -2.57936521
## [232,]   1.68782109
## [233,]   1.16856851
## [234,]   3.01683165
## [235,]   0.11639234
## [236,]   0.19192982
## [237,]  -3.78149419
## [238,]   0.88590208
## [239,]  -1.12304666
## [240,]   2.94478720
## [241,]   4.20256925
## [242,]   3.79874042
## [243,] -11.46159974
## [244,]  -4.15330112
## [245,]  -1.21540941
## [246,]  -9.07267943
## [247,]  -3.89594464
## [248,]   0.86636012
## [249,]  -2.19046981
## [250,]  -1.97030516
## [251,]   0.97509011
## [252,]   2.32693538
## [253,]   4.12186437
## [254,]   0.75407704
## [255,]   0.52988330
## [256,]   3.18566623
## [257,]   0.47227201
## [258,]   2.94657785
## [259,]   0.95578752
## [260,]   2.01392090
## [261,]  -0.49353973
## [262,]   0.46813035
## [263,]   2.09411698
## [264,]  -2.12381900
## [265,]  -0.06370765
## [266,]  -1.04251300
## [267,]   0.62164263
## [268,]  -1.66070995
## [269,]   5.58122105
## [270,]   1.65462659
## [271,]   1.35509650
## [272,]   3.36255971
## [273,]   4.36153906
## [274,]   4.92642409
## [275,]   2.78770237
## [276,]   3.90089954
## [277,]  -0.73220242
## [278,]   0.53958771
## [279,]  -0.14167754
## [280,]   4.33429647
## [281,]   2.61240952
## [282,]   2.07209030
## [283,]   0.37733034
## [284,]   0.11823990
## [285,]   0.23340464
## [286,]  -0.56299481
## [287,]  -1.32037540
## [288,]  -3.87628262
## [289,]  -0.28565880
## [290,]  -0.38550981
## [291,]  -3.05645820
## [292,]  -0.76813621
## [293,]  -2.98029020
## [294,]  -4.97106775
## [295,]  -0.80975997
## [296,]  -3.71028228
## [297,]  -6.29688711
## [298,]  -3.31002226
## [299,]  -2.70700479
## [300,]  -4.55416366
## [301,]  -4.62948987
## [302,]  -1.00450418
## [303,]  -7.19163019
## [304,]  -2.44901141
## [305,]  -3.56639016
## [306,]  -2.15788028
## [307,]  -6.88221912
## [308,] -11.81281751
## [309,]  -6.82662340
## [310,]  -2.04295734
## [311,]  -6.34041015
## [312,]  -2.10282947
## [313,]  -1.40049872
## [314,]  -0.20232730
## [315,]   2.58998350
## [316,]  -4.95183725
## [317,]  -3.95192342
## [318,]  -3.86768545
## [319,]  -9.67485116
## [320,]  -3.17973394
## [321,] -16.25565835
## [322,]  -3.28256094
## [323,] -10.47974988
## [324,] -13.19428012
## [325,] -13.66070306
## [326,] -10.83482685
## [327,]  -6.21298216
## [328,] -12.90503935
## [329,]  -3.79601597
## [330,]   2.11668159
## [331,]  -9.84339199
## [332,]   3.70212678
## [333,]  -7.86925116
## [334,]  -3.41658897
## [335,]   0.06608472
## [336,]  -0.21180645
## [337,]   0.33483096
## [338,]   1.23509008
## [339,]  -2.11464757
## [340,]  -6.51066987
## [341,]  -7.33640929
## [342,]  -2.61777122
## [343,]  -1.86894575
## [344,]  -5.97151093
## [345,]  -6.91211851
## [346,]  -3.21244123
## [347,]  -4.86746876
## [348,]  -3.74508420
## [349,]  -1.11822031
## [350,]  -3.49893751
## [351,]  -4.36478674
## [352,]  -3.86561390
## [353,]  -6.87485532
## [354,]  -4.63368334
## [355,]  -4.71186095
## [356,]  -6.77327957
## [357,]  -1.82064081
## [358,]  -0.84924541
## [359,]  -1.73058441
## [360,]  -8.13768042
## [361,]   3.45930053
## [362,]   3.91307029
## [363,]  -1.46786177
## [364,]  -0.62953154
## [365,]  -6.32191833
## [366,]  -4.09992014
## [367,]  -1.92567746
## [368,]  -1.43854041
## [369,]   0.89082449
## [370,]  -5.41549367
## [371,]  -6.37458714
## [372,]  -0.07027041
## [373,]  -7.68759346
## [374,]  -6.01102628
## [375,]  -7.04798797
## [376,]  -6.64069900
## [377,]  -4.69543672
## [378,]  -6.94007534
## [379,]  -0.95627894
## [380,]  -7.12626818
## [381,]  -1.56259100
## [382,] -14.34199262
## [383,]   0.31733394
## [384,]   1.66435658
## [385,]  -6.19363836
## [386,]  -8.03775475
## [387,]  -2.55764599
## [388,]  -1.43297264
## [389,] -13.41546919
## [390,]  -3.60930947
## [391,]  -1.20586132
## [392,]  -4.85085028
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{e2 <-}\StringTok{ }\KeywordTok{sum}\NormalTok{(e^}\DecValTok{2}\NormalTok{)}
\NormalTok{e2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6979.413
\end{verbatim}


\end{document}
