---
title: "R Notebook"
output: html_notebook
---

Chapter 7 Homework HW 7.2 and 7.5

7.2 Friedman (1991) introduced several benchmark data sets created by simulation. One of these simulations used the following nonlinear equation to create data:

$$y = 10sin(\pi x_1 x_2) + 20(x_3 -0.5)^2+10x_4 +5x_5 + N(0,\sigma^2)$$
where the ex values are random variables uniformly distributed between [0,1] (there are also 5 0ther non-informative variables also created in simulation). The package mlbench contains a funciton called mlbench.friedman1 that simulats these data:

```{r}
library(mlbench)
set.seed(200)
trainingData <- mlbench.friedman1(200, sd = 1)
trainingData$x <- data.frame(trainingData$x)
#featurePlot(trainingData$x, trainingData$y)
testData <- mlbench.friedman1(5000, sd = 1)
testData$x <- data.frame(testData$x)
```

Tune several modesl on these data.

Which models appear to give the best performance? Does MARS select informative predictors (those named X1-X15).

7.5 Exercise 6.3 describes data for a chemical manufacturing process. Use the same data imputation, data splitting, and pre-processing steps as before and train several nonlinear regression models.

a. Which nonlinear regressoin model gives the optimal resampling and test set performance?

b. Which predictors are the moost important in the optimal nonlinear regressoin model? Do either the biological or process variables dominatre the list? How do the top ten important predictors compare to the top ten predictors from the optimal linear model?

c. Explore the reltionships between the top predicrotres and the response for the predictors that are unique to the optimale nonlinear regression model. Do these plots reveal intuition about the biological or process predictors and their relationship with yield? 
